config/routes.rb
JsViews::Application.routes.draw do
  resources :dogs
  root 'dogs#index'
end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  respond_to :html

  def new
    @dog = Dog.new
    render(partial: 'new')
  end

  def create
    @dog = Dog.create(dog_parameters)
    render(partial: 'show')
  end

  def show
    @dog = Dog.find(params[:id])
    render(partial: 'show')
  end

  def edit
    @dog = Dog.find(params[:id])
    render(partial: 'edit')
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update_attributes(dog_parameters)
    render(partial: 'show')
  end

  def destroy
    Dog.destroy(params[:id])
    render(partial: 'index', locals: {dogs: Dog.all})
  end

  def index
    @dogs = Dog.all
  end

  private
  def dog_parameters
    params.require(:dog).permit(:name, :breed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/_dog.html.erb
<%= content_tag_for(:tr, dog) do %>
  <td><%= link_to(dog.name, dog, remote: true) %></td>
  <td><%= dog.breed %></td>
  <td><%= link_to("Edit", edit_dog_path(dog), remote: true, class: "edit-link") %></td>
  <td><%= link_to("Delete", dog_path(dog), remote: true, method: :delete, class: "delete-link") %></td>
<% end %>

app/views/dogs/_edit.html.erb
<%= form_for(@dog, remote: true) do |f| %>
  <div>Name: <%= f.text_field :name %></div>
  <div>Breed: <%= f.text_field :breed %></div>
  <div><%= f.submit %></div>
<% end %>

app/views/dogs/_index.html.erb
<%= render(dogs) %>

app/views/dogs/_new.html.erb
<%= form_for(@dog, remote: true, disable_with: "Submitting...") do |f| %>
  <div>Name: <%= f.text_field :name %></div>
  <div>Breed: <%= f.text_field :breed %></div>
  <div><%= f.submit %></div>
<% end  %>

app/views/dogs/_show.html.erb
<h1><%= @dog.name %></h1>
<h2>The <%= @dog.breed %></h2>

app/views/dogs/edit.html.erb
<%= form_for(@dog, remote: true) do |f| %>
  <div>Name: <%= f.text_field :name %></div>
  <div>Breed: <%= f.text_field :breed %></div>
  <div><%= f.submit %></div>
<% end %>

app/views/dogs/index.html.erb
<h1>All the Dogs</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody id="dog-list">
    <%= render(partial: 'dogs/index', locals: {dogs: @dogs}) %>
  </tbody>
</table>
<%= link_to("New Dog", new_dog_path, remote: true, id: "new-dog-link") %>
<hr />
<div id="dog-form"></div>
<div id="dog-show"></div>

app/views/dogs/new.html.erb
<%= form_for(@dog, remote: true, disable_with: "Submitting...") do |f| %>
  <div>Name: <%= f.text_field :name %></div>
  <div>Breed: <%= f.text_field :breed %></div>
  <div><%= f.submit %></div>
<% end  %>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>
<h2>The <%= @dog.breed %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JsViews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <style>
    .error, .alert {
      background-color: rgb(255, 168, 162);
    }
    .notice, .success {
      background-color: lightgreen;
    }
  </style>
</head>
<body>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= yield %>

</body>
</html>